#!/bin/sh

MOD='mozmp';
CVSMOD='MOZMP';
SRCDIR=/home/petejc;
DIR=`pwd`

cd $DIR/chrome;

cat $SRCDIR/$CVSMOD/$MOD/source/installed-chrome.txt >> installed-chrome.txt;

cd $DIR/chrome/

ln -s $SRCDIR/$CVSMOD/$MOD/source/$MOD/ $MOD

printf "finished creating sym links for $MOD\n\n";
